standalone functional enum + standard kernel/functional conv to/fro string
wavefunction91/ExchCXX pull request #10
Opened 2020-11-21 14:03 UTC by evaleev

2020-11-21 14:04 UTC, evaleev commented on include/exchcxx/util/bidirectional_map.hpp
> +class BidirectionalMap{
improvements:
- `to_val` -> `value`
- `to_key` -> `key`
- add `value_exists` and `key_exists`

2020-11-21 20:24 UTC, samslattery commented on include/exchcxx/util/bidirectional_map.hpp
> +class BidirectionalMap{
Made these changes.

2020-11-30 18:05 UTC, wavefunction91 requested changes

2020-11-30 18:05 UTC, wavefunction91 commented on include/exchcxx/enums/functionals.hpp
> +extern BidirectionalMap<std::string, Functional> functional_map;
@samslattery @evaleev I take it the reason you guys are exposing this is to do something like this in MPQC?
```
XCFunctional func( functional_map.val("MyFunctional") );
```

Is there any particular reason you chose this vs defining a `XCFunctional(std::string)` ctor and keep the definition of the map source private?

2020-11-30 18:05 UTC, wavefunction91 commented on include/exchcxx/util/bidirectional_map.hpp
> +template <typename Key, typename Val>
I would also expose (defaulted) `Compare` template args here for both the injection and surjection. This would allow for the extension to case-insensitive `std::string` maps in the future (which would be desirable from a user input perspective)

2020-11-30 18:05 UTC, wavefunction91 commented on include/exchcxx/util/bidirectional_map.hpp
> +    }
This implies the the map is bijective, otherwise it will lead to unexpected (but well-defined) behaviour.

https://en.cppreference.com/w/cpp/container/map/insert

I would add a quick check that there are no duplicates in the `Value`'s and throw an exception if there are.

2020-11-30 18:05 UTC, wavefunction91 commented on src/xc_functional.cxx
> +BidirectionalMap<std::string, Functional> functional_map{{{"SVWN3", Functional::SVWN3},
Align this with the subsequent lines (I'll add a linter for this at some point...)

2020-11-30 18:07 UTC, wavefunction91 commented
@samslattery @evaleev Come to think of it, we should probably add UT's for this to make sure we have full coverage of the supported Functionals (and Kernels for that matter)

2020-12-31 13:54 UTC, evaleev commented on include/exchcxx/enums/functionals.hpp
> +extern BidirectionalMap<std::string, Functional> functional_map;
@wavefunction91 I think many use cases become easier with meta-info like this map accessible programmatically (e.g. being able to validate XCFunctional inputs strings if exceptions are forbidden, etc.) rather than embedded into dox.

2020-12-31 13:55 UTC, evaleev commented on include/exchcxx/util/bidirectional_map.hpp
> +template <typename Key, typename Val>
good idea, @samslattery please implement

2020-12-31 13:55 UTC, evaleev commented on include/exchcxx/util/bidirectional_map.hpp
> +    }
@samslatter please address

2020-12-31 13:56 UTC, evaleev commented on src/xc_functional.cxx
> +BidirectionalMap<std::string, Functional> functional_map{{{"SVWN3", Functional::SVWN3},
@samslattery please address

2021-01-05 15:54 UTC, samslattery commented on include/exchcxx/util/bidirectional_map.hpp
> +    }
Added check for duplicates.

2021-01-05 15:54 UTC, samslattery commented on src/xc_functional.cxx
> +BidirectionalMap<std::string, Functional> functional_map{{{"SVWN3", Functional::SVWN3},
Made formatting better.

2021-01-05 15:56 UTC, samslattery commented on include/exchcxx/util/bidirectional_map.hpp
> +template <typename Key, typename Val>
Added these template parameters, with defaults of `std::less<Key>` and `std::less<Val>`

2021-01-05 18:38 UTC, wavefunction91 approved these changes

2021-01-05 18:38 UTC, merged