Sycl cleanup
wavefunction91/ExchCXX pull request #21
Opened 2022-07-14 11:46 UTC by abagusetty

Allows SYCL to be valid on Intel, NV, HIP devices

2022-07-14 13:53 UTC, wavefunction91 requested changes

2022-07-14 13:53 UTC, wavefunction91 commented on test/CMakeLists.txt
> +set(SYCL_FLAGS -fsycl -fsycl-unnamed-lambda -fsycl-device-code-split=per_kernel) # -fsycl-targets=spir64_gen -Xsycl-target-backend "-device 12.1.0,12.4.0")
I see that this is in another place as well. If this is something that needs to persist, we need to place it behind `GAUXC_ENABLE_SYCL` barriers.

2022-07-18 16:25 UTC, wavefunction91 requested changes

2022-07-18 16:25 UTC, wavefunction91 commented on machine/sycl_A100_sm80_toolchain.cmake
> +set( CMAKE_C_COMPILER   clang )
I agree that we should have this kind of toolchain management in general, but it's a bit asymmetric - if we're going to do this I'd want to do it "right" and add configs for all the machines we're planning on supporting.

I'll have you remove these from the repo for now (but keep them around) and we can add a new Issue/PR to address this in the future.

2022-07-18 16:25 UTC, wavefunction91 commented on src/CMakeLists.txt
> +  target_compile_features( exchcxx PUBLIC cxx_std_17 )
I would place this closer to the `cxx_std_14` line (ln 18 in this file). Something like
```
if(EXCHCXX_ENABLE_SYCL)
  target_compile_features( exchcxx PUBLIC cxx_std_17 )
else()
  target_compile_features( exchcxx PUBLIC cxx_std_14 )
endif()
```

This is just to place standards decisions all in one place (i.e. so we don't have the dig for it later when/if we update)

2022-07-18 16:25 UTC, wavefunction91 commented on src/sycl/exchcxx_sycl.cmake
> +#set(SYCL_FLAGS -fsycl -fsycl-unnamed-lambda -fsycl-device-code-split=per_kernel -fsycl-targets=spir64_gen -Xsycl-target-backend "-device 12.1.0,12.4.0")
Delete these

2022-07-18 16:25 UTC, wavefunction91 commented on src/sycl/exchcxx_sycl.cmake
> +target_compile_options( exchcxx
And this

2022-07-18 16:25 UTC, wavefunction91 commented on src/sycl/exchcxx_sycl.cmake
> +target_link_libraries( exchcxx PUBLIC ${SYCL_FLAGS} )
And this

2022-07-18 16:25 UTC, wavefunction91 commented on src/sycl/exchcxx_sycl.cmake
> -#target_link_libraries( exchcxx PUBLIC SYCL::SYCL )
Has these been any work on CMake discovery for SYCL? Ideally, we'd have a target / language that we could encapsulate in a TARGET rather than throwing around explicit flags. I think that's how it was done originally

2022-07-20 21:41 UTC, abagusetty commented on src/CMakeLists.txt
> +  target_compile_features( exchcxx PUBLIC cxx_std_17 )
Done

2022-07-20 21:42 UTC, abagusetty commented on src/sycl/exchcxx_sycl.cmake
> -#target_link_libraries( exchcxx PUBLIC SYCL::SYCL )
Since SYCL was never considered as a language by CMake, I dont think we will ever need this. usual compiler and link options needs to be appended with CXX_FLAGS, like same old days.

2022-07-20 22:18 UTC, wavefunction91 commented on src/sycl/exchcxx_sycl.cmake
> -#target_link_libraries( exchcxx PUBLIC SYCL::SYCL )
Not exactly - appending CMAKE_<LANG>_FLAGS globally is generally bad practice, it needs to be encapsulated into a TARGET (e.g. `SYCL::SYCL` as we had previously). We need to either use a stock `FindSYCL` or write one ourselves.

2022-10-04 16:42 UTC, wavefunction91 submitted a review, later dismissed

2022-10-04 16:48 UTC, wavefunction91 approved these changes

2022-10-04 16:49 UTC, merged