Add Builtin LDA Electron-Proton Correlation Functionals
wavefunction91/ExchCXX pull request #38
Opened 2024-05-02 22:34 UTC by aodongliu

This PR added LDA electron-proton correlation functionals and kernels using Builtin backend. These are for nuclear-electronic orbital DFT method. 

The functionals include: EPC17-1, EPC17-2, EPC18-1, EPC18-2

This PR partially address [issue35](https://github.com/wavefunction91/ExchCXX/issues/35) by first adding in the LDA epc functionals. The GGA epc functional (epc19) is in preparation and will be merged later.

2024-05-02 23:28 UTC, wavefunction91 requested changes
Still need to look at the unit tests more carefully, but this should be a good round of things to look at. I'll check out the tests tomorrow.

2024-05-02 23:28 UTC, wavefunction91 commented on make_command.sh
> +cmake -DCMAKE_BUILD_TYPE=Debug -DGAUXC_ENABLE_OPENMP=off -DGAUXC_ENABLE_MPI=off ..
Remove this file

2024-05-02 23:28 UTC, wavefunction91 commented on src/libxc.cxx
> +
This seems wrong

2024-05-02 23:28 UTC, wavefunction91 commented on test/reference_values.cxx
> +// Incorrect EPC Reference Values!
If these are incorrect, why add them at all?

2024-05-03 01:04 UTC, aodongliu commented on src/libxc.cxx
> +
What's the best way of handling this at this moment?

2024-05-03 01:04 UTC, aodongliu commented on test/reference_values.cxx
> +// Incorrect EPC Reference Values!
removed the ground truth comparison

2024-05-03 01:22 UTC, wavefunction91 commented on src/libxc.cxx
> +
Since there's only 4 EPC's in Libxc, I'd just check if the internal Libxc ID is one of those 4. It's not scalable, but until there's proper infra for EPC's in Libxc, there's really no other option (returning false is just incorrect).

2024-05-03 16:40 UTC, wavefunction91 requested changes
Small requests, other than that LGTM.

2024-05-03 16:40 UTC, wavefunction91 commented on test/xc_kernel_test.cxx
> +    XCKernel lda( backend, epc_lda_kernel_test, Spin::Polarized );
Just because I don't know where else to put the comment: we need to add logic somewhere that throws if EPC functionals are constructed w/o `Polarized`.

2024-05-03 16:40 UTC, wavefunction91 commented on test/xc_kernel_test.cxx
> +  if( func_builtin.is_epc() ) return;
I would move this logic to the calling locations - this is just asking for problems in the event that we ever want ground-truth comparisons with EPC functionals. At least it's _**very**_ visible if you put it in the calling locations.

2024-05-03 17:37 UTC, wavefunction91 requested changes

2024-05-03 17:37 UTC, wavefunction91 commented on src/libxc.cxx
> +  return xcNumber == 328 or xcNumber == 329 or xcNumber == 330 or xcNumber or 331;
Please use the Libxc identifiers

2024-05-03 19:42 UTC, wavefunction91 commented on src/libxc.cxx
> +  return xcNumber == 328 or xcNumber == 329 or xcNumber == 330 or xcNumber or 331;
Oh, never mind, that's obviously not version proof since they don't have them in 6.x.y - I suppose the only  way around that is to version check this code, and only check the Libxc identifiers if the major version is > 7 (see other places in the code where we check that logic)

2024-05-03 20:57 UTC, aodongliu commented on test/xc_kernel_test.cxx
> +    XCKernel lda( backend, epc_lda_kernel_test, Spin::Polarized );
How about checking this before generating the kernel, in `gen_from_kern`?

2024-05-03 21:07 UTC, wavefunction91 requested changes

2024-05-03 21:07 UTC, wavefunction91 commented on src/libxc.cxx
> +  xcNumber == 328 or xcNumber == 329 or xcNumber == 330 or xcNumber or 331;
This needs to just be `false` for pre-7, I'm not sure if those are assigned in pre-7, which could lead to false positives

2024-05-03 21:12 UTC, aodongliu commented on src/libxc.cxx
> +  xcNumber == 328 or xcNumber == 329 or xcNumber == 330 or xcNumber or 331;
Done. 
They are not assigned in libxc 6.x.y (there's a gap between 327~387) but just to be save it should just return false.

2024-05-03 22:42 UTC, wavefunction91 approved these changes

2024-05-03 22:42 UTC, merged